table Dim_Country
	lineageTag: 2281402c-342c-43eb-aa75-71cf999c4102

	column code
		dataType: string
		lineageTag: 87929c46-07ce-45a9-b8d6-89420b292318
		summarizeBy: none
		sourceColumn: code

		annotation SummarizationSetBy = Automatic

	column country_name
		dataType: string
		lineageTag: ede7f458-ad0b-4a4f-936a-c9df7e940655
		summarizeBy: none
		sourceColumn: country_name

		annotation SummarizationSetBy = Automatic

	partition Dim_Country = m
		mode: import
		source =
				let
				  Source = #table(
				    {"code", "country_name"},
				    {
				      {"AUT", "Austria"},
				      {"BEL", "Belgium"},
				      {"BLR", "Belarus"},
				      {"BOL", "Bolivia"},
				      {"BRA", "Brazil"},
				      {"CAN", "Canada"},
				      {"COL", "Colombia"},
				      {"CRI", "Costa Rica"},
				      {"CZE", "Czechia"},
				      {"DEU", "Germany"},
				      {"ESP", "Spain"},
				      {"FIN", "Finland"},
				      {"GBR", "United Kingdom"},
				      {"GEO", "Georgia"},
				      {"GRC", "Greece"},
				      {"IDN", "Indonesia"},
				      {"IRN", "Iran"},
				      {"ISR", "Israel"},
				      {"ITA", "Italy"},
				      {"JPN", "Japan"},
				      {"MNE", "Montenegro"},
				      {"PER", "Peru"},
				      {"ROU", "Romania"},
				      {"RUS", "Russia"},
				      {"SWE", "Sweden"},
				      {"THA", "Thailand"},
				      {"UKR", "Ukraine"},
				      {"USA", "United States"}
				    }
				  ),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(Source, {{"code", type text}, {"country_name", type text}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_ResultType = Table

