table Dim_Region
	lineageTag: 9d055d90-c174-4475-91dd-c3c37e8abdf1

	column region_id
		dataType: string
		lineageTag: ac794ec9-eb70-443b-a51d-92f7e4232db8
		summarizeBy: none
		sourceColumn: region_id

		annotation SummarizationSetBy = Automatic

	column code
		dataType: string
		lineageTag: deb3cc4f-bc0b-4ee9-acec-9bf8b26204e4
		summarizeBy: none
		sourceColumn: code

		annotation SummarizationSetBy = Automatic

	column geo_code
		dataType: string
		lineageTag: e97af709-4a32-4ac8-a979-465ee68fdee1
		summarizeBy: none
		sourceColumn: geo_code

		annotation SummarizationSetBy = Automatic

	column geo_name
		dataType: string
		lineageTag: 46c109bd-411b-46e8-b643-b90eb67cb4b6
		summarizeBy: none
		sourceColumn: geo_name

		annotation SummarizationSetBy = Automatic

	column region_label
		dataType: string
		lineageTag: 537cc7b2-2d10-4958-9746-ccb038d9f968
		summarizeBy: none
		sourceColumn: region_label

		annotation SummarizationSetBy = Automatic

	partition Dim_Region = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents("C:\Users\vitor\Documents\Portfolio\Projects\P1\outputs\07.2_powerbi_model.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "Dim_Region", Kind = "Sheet"]}[Data],
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(#"Navegação 1", [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"region_id", type text}, {"code", type text}, {"geo_code", type text}, {"geo_name", type text}, {"region_label", type text}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

