table RVC_Variance
	lineageTag: b48003d8-8517-4df4-b43b-e126ccdc4134

	column variable
		dataType: string
		lineageTag: 4c94e880-b0f3-42bd-b40c-d89acf464eca
		summarizeBy: none
		sourceColumn: variable

		annotation SummarizationSetBy = Automatic

	column variable_label
		dataType: string
		lineageTag: f4e243c3-9701-43fc-9b4d-7f71fe6f2c39
		summarizeBy: none
		sourceColumn: variable_label

		annotation SummarizationSetBy = Automatic

	column variable_group
		dataType: string
		lineageTag: 18a6b4c1-710f-4137-bde2-c8cefc72aed4
		summarizeBy: none
		sourceColumn: variable_group

		annotation SummarizationSetBy = Automatic

	column eta2
		dataType: double
		lineageTag: 95de2eb7-def7-4168-b2d7-3586d85b07e3
		summarizeBy: sum
		sourceColumn: eta2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column within_share
		dataType: double
		lineageTag: 7ee31684-1593-4eea-b6a6-db75d0d537f5
		summarizeBy: sum
		sourceColumn: within_share

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column epsilon2
		dataType: double
		lineageTag: 84155cd7-ddb7-4e2d-a7f9-33e68c15af26
		summarizeBy: sum
		sourceColumn: epsilon2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column perm_p
		dataType: double
		lineageTag: 1d47491f-151a-449d-be19-72e995fba845
		summarizeBy: sum
		sourceColumn: perm_p

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition RVC_Variance = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents("C:\Users\vitor\Documents\Portfolio\Projects\P1\outputs\07.3_region_vs_country.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "RVC_Variance", Kind = "Sheet"]}[Data],
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(#"Navegação 1", [PromoteAllScalars = true]),
				  #"Colunas selecionadas" = Table.SelectColumns(#"Cabeçalhos promovidos", {"variable", "variable_label", "variable_group", "eta2", "within_share", "epsilon2", "perm_p"}),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Colunas selecionadas", {{"variable", type text}, {"variable_label", type text}, {"variable_group", type text}, {"eta2", type number}, {"within_share", type number}, {"epsilon2", type number}, {"perm_p", type number}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

