table Conv_Feature
	lineageTag: 5e660df8-da4c-4ecf-ae33-673882496b55

	column flow
		dataType: string
		lineageTag: 16d58941-3daf-40ad-8a37-369ba04861f8
		summarizeBy: none
		sourceColumn: flow

		annotation SummarizationSetBy = Automatic

	column converging_regions_in_flow
		dataType: int64
		formatString: 0
		lineageTag: 647c7628-4249-4afc-8a66-2498badf1805
		summarizeBy: sum
		sourceColumn: converging_regions_in_flow

		annotation SummarizationSetBy = Automatic

	column median_contribution
		dataType: double
		lineageTag: 7108922f-9a09-45ed-854d-c173c014b20d
		summarizeBy: sum
		sourceColumn: median_contribution

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mean_contribution
		dataType: double
		lineageTag: 9845342a-4f99-43c9-b3c1-b8abf38d13c5
		summarizeBy: sum
		sourceColumn: mean_contribution

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column regions_positive_contribution
		dataType: int64
		formatString: 0
		lineageTag: bcc4f16d-9ebd-44bf-b175-d38b05b72f8c
		summarizeBy: sum
		sourceColumn: regions_positive_contribution

		annotation SummarizationSetBy = Automatic

	column consistency_pct
		dataType: double
		lineageTag: a2ad6aa6-14ee-4cff-b138-fe504e2d9acb
		summarizeBy: sum
		sourceColumn: consistency_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column feature
		dataType: string
		lineageTag: bb516e05-7c5f-4474-ad8f-ee689f6f09b3
		summarizeBy: none
		sourceColumn: feature

		annotation SummarizationSetBy = Automatic

	column family
		dataType: string
		lineageTag: 06267c93-aff7-4247-89a8-8d051447ba90
		summarizeBy: none
		sourceColumn: family

		annotation SummarizationSetBy = Automatic

	column aggregation_scope
		dataType: string
		lineageTag: 1f425272-be00-48cd-ae65-a60fcf1f9f99
		summarizeBy: none
		sourceColumn: aggregation_scope

		annotation SummarizationSetBy = Automatic

	partition Conv_Feature = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents("C:\Users\vitor\Documents\Portfolio\Projects\P1\outputs\07.2_powerbi_model.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "Conv_Feature", Kind = "Sheet"]}[Data],
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(#"Navegação 1", [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"flow", type text}, {"converging_regions_in_flow", Int64.Type}, {"median_contribution", type number}, {"mean_contribution", type number}, {"regions_positive_contribution", Int64.Type}, {"consistency_pct", type number}, {"feature", type text}, {"family", type text}, {"aggregation_scope", type text}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

