table Country_Ref_Region
	lineageTag: 637e03f5-1a0d-4ec6-bc8d-43b24d0476df

	column region_id
		dataType: string
		lineageTag: 599a1763-2a47-4976-a024-99a1e32a72a9
		summarizeBy: none
		sourceColumn: region_id

		annotation SummarizationSetBy = Automatic

	column code
		dataType: string
		lineageTag: 41bd52b4-cbf3-4f8e-ad45-bce11868d8ad
		summarizeBy: none
		sourceColumn: code

		annotation SummarizationSetBy = Automatic

	column geo_code
		dataType: string
		lineageTag: e195527b-592c-4531-bd9b-32b667da42b7
		summarizeBy: none
		sourceColumn: geo_code

		annotation SummarizationSetBy = Automatic

	column geo_name
		dataType: string
		lineageTag: 729647a8-396b-434e-8101-3a02718fc806
		summarizeBy: none
		sourceColumn: geo_name

		annotation SummarizationSetBy = Automatic

	column own_country_distance
		dataType: double
		lineageTag: 7f09b481-f199-441e-b8c5-789ce5e03d26
		summarizeBy: sum
		sourceColumn: own_country_distance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column own_country_rank
		dataType: int64
		formatString: 0
		lineageTag: ff706f1e-92e9-4184-8b68-319edea22d75
		summarizeBy: sum
		sourceColumn: own_country_rank

		annotation SummarizationSetBy = Automatic

	column own_country_reference_method
		dataType: string
		lineageTag: f4f56699-b5c1-48c8-aee3-6362c1a7fe10
		summarizeBy: none
		sourceColumn: own_country_reference_method

		annotation SummarizationSetBy = Automatic

	column own_country_reference_regions
		dataType: int64
		formatString: 0
		lineageTag: 47796e0c-d169-41b6-858e-fc3620f3425e
		summarizeBy: sum
		sourceColumn: own_country_reference_regions

		annotation SummarizationSetBy = Automatic

	column nearest_other_country_code
		dataType: string
		lineageTag: f1e7581e-e370-401d-bbcd-f02418734df4
		summarizeBy: none
		sourceColumn: nearest_other_country_code

		annotation SummarizationSetBy = Automatic

	column nearest_other_country_distance
		dataType: double
		lineageTag: 2ce887d4-e2c9-474c-85db-0326fcb783b0
		summarizeBy: sum
		sourceColumn: nearest_other_country_distance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nearest_reference_country_code
		dataType: string
		lineageTag: 1e1fdc6d-143b-4c50-b3cf-453a88fb2739
		summarizeBy: none
		sourceColumn: nearest_reference_country_code

		annotation SummarizationSetBy = Automatic

	column nearest_reference_is_own_country
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4e8f1e54-68c7-4b39-b6c2-06a8b8bcdc62
		summarizeBy: none
		sourceColumn: nearest_reference_is_own_country

		annotation SummarizationSetBy = Automatic

	column nearest_reference_distance
		dataType: double
		lineageTag: 4c39398b-7965-4f54-b08e-7e107f3b161d
		summarizeBy: sum
		sourceColumn: nearest_reference_distance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column own_minus_nearest_other_distance
		dataType: double
		lineageTag: 02922863-b73e-4ae1-9bfd-86e43d6c8e5e
		summarizeBy: sum
		sourceColumn: own_minus_nearest_other_distance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Country_Ref_Region = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents("C:\Users\vitor\Documents\Portfolio\Projects\P1\outputs\07.2_powerbi_model.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "Country_Ref_Region", Kind = "Sheet"]}[Data],
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(#"Navegação 1", [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"region_id", type text}, {"code", type text}, {"geo_code", type text}, {"geo_name", type text}, {"own_country_distance", type number}, {"own_country_rank", Int64.Type}, {"own_country_reference_method", type text}, {"own_country_reference_regions", Int64.Type}, {"nearest_other_country_code", type text}, {"nearest_other_country_distance", type number}, {"nearest_reference_country_code", type text}, {"nearest_reference_is_own_country", type logical}, {"nearest_reference_distance", type number}, {"own_minus_nearest_other_distance", type number}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

