table Dim_Family
	lineageTag: 304bacea-062a-48a5-bea9-9a7ab088d503

	column family
		dataType: string
		lineageTag: 018a0fd7-22f4-4b28-8f8f-fa5712483b2a
		summarizeBy: none
		sourceColumn: family

		annotation SummarizationSetBy = Automatic

	column family_label
		dataType: string
		lineageTag: 5733303e-9c55-47d3-b51a-6248e81d4a06
		summarizeBy: none
		sourceColumn: family_label

		annotation SummarizationSetBy = Automatic

	column family_sort
		dataType: int64
		formatString: 0
		lineageTag: 5bf9ff95-b9cc-43ea-8e79-30b2b46696e1
		summarizeBy: sum
		sourceColumn: family_sort

		annotation SummarizationSetBy = Automatic

	partition Dim_Family = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents("C:\Users\vitor\Documents\Portfolio\Projects\P1\outputs\07.2_powerbi_model.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "Dim_Family", Kind = "Sheet"]}[Data],
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(#"Navegação 1", [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"family", type text}, {"family_label", type text}, {"family_sort", Int64.Type}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

