table Dim_Indicator
	lineageTag: 7ef8a886-38ba-4da0-8b8b-b7f7639e8cc3

	column variable
		dataType: string
		lineageTag: 2af5a574-172f-40cb-89da-853ac3e86d54
		summarizeBy: none
		sourceColumn: variable

		annotation SummarizationSetBy = Automatic

	column feature
		dataType: string
		lineageTag: 0705938f-48de-465d-a2ac-3308bde27874
		summarizeBy: none
		sourceColumn: feature

		annotation SummarizationSetBy = Automatic

	column family
		dataType: string
		lineageTag: cb08a276-964f-4603-a169-e8667a384a85
		summarizeBy: none
		sourceColumn: family

		annotation SummarizationSetBy = Automatic

	column component_kind
		dataType: string
		lineageTag: ee462cc9-fa04-4880-941b-9013f6e5650f
		summarizeBy: none
		sourceColumn: component_kind

		annotation SummarizationSetBy = Automatic

	column common_weight
		dataType: double
		lineageTag: ae482980-22b9-4ede-8d49-ac8d62406464
		summarizeBy: sum
		sourceColumn: common_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column indicator_label
		dataType: string
		lineageTag: e66d2f82-87b8-41c3-ad43-efe7bb2afa83
		summarizeBy: none
		sourceColumn: indicator_label

		annotation SummarizationSetBy = Automatic

	column indicator_sort
		dataType: int64
		formatString: 0
		lineageTag: 917549db-2d56-4eea-b789-d8f328d50e71
		summarizeBy: sum
		sourceColumn: indicator_sort

		annotation SummarizationSetBy = Automatic

	column profile_value_basis
		dataType: string
		lineageTag: 41bb816b-8f3a-4a1e-8fd0-c112338952a0
		summarizeBy: none
		sourceColumn: profile_value_basis

		annotation SummarizationSetBy = Automatic

	column interpretation_role
		dataType: string
		lineageTag: 9ef1d46c-dba8-4d00-9ed9-3e0b43aad72c
		summarizeBy: none
		sourceColumn: interpretation_role

		annotation SummarizationSetBy = Automatic

	partition Dim_Indicator = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents("C:\Users\vitor\Documents\Portfolio\Projects\P1\outputs\07.2_powerbi_model.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "Dim_Indicator", Kind = "Sheet"]}[Data],
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(#"Navegação 1", [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"variable", type text}, {"feature", type text}, {"family", type text}, {"component_kind", type text}, {"common_weight", type number}, {"indicator_label", type text}, {"indicator_sort", Int64.Type}, {"profile_value_basis", type text}, {"interpretation_role", type text}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

