table Feature_Annual
	lineageTag: eff5eea1-a34c-4d8a-b652-95b2f370035a

	column cluster
		dataType: int64
		formatString: 0
		lineageTag: 33e23116-5488-4972-9ae6-7e47d3ca7c72
		summarizeBy: sum
		sourceColumn: cluster

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: 3ae7744d-852e-4831-b6dc-88995145d008
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column feature
		dataType: string
		lineageTag: db01b144-0da8-4085-8fb5-578087a5d39e
		summarizeBy: none
		sourceColumn: feature

		annotation SummarizationSetBy = Automatic

	column weighted_mean
		dataType: double
		lineageTag: 5512adcc-fa58-4d74-94d2-4f790e95016f
		summarizeBy: sum
		sourceColumn: weighted_mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weighted_median
		dataType: double
		lineageTag: d91a30b7-2d4d-4e6a-b33a-aba2c84be678
		summarizeBy: sum
		sourceColumn: weighted_median

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weighted_q25
		dataType: double
		lineageTag: fdc00dd8-3fce-4fdf-9388-4fc16551aafe
		summarizeBy: sum
		sourceColumn: weighted_q25

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weighted_q75
		dataType: double
		lineageTag: 4e57b655-378d-483d-8801-cb366deb844f
		summarizeBy: sum
		sourceColumn: weighted_q75

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weighted_sd
		dataType: double
		lineageTag: e49ed0ac-a881-4929-b7d7-9977b40fa571
		summarizeBy: sum
		sourceColumn: weighted_sd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Feature_Annual = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents("C:\Users\vitor\Documents\Portfolio\Projects\P1\outputs\07.2_powerbi_model.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "Feature_Annual", Kind = "Sheet"]}[Data],
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(#"Navegação 1", [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"cluster", Int64.Type}, {"year", Int64.Type}, {"feature", type text}, {"weighted_mean", type number}, {"weighted_median", type number}, {"weighted_q25", type number}, {"weighted_q75", type number}, {"weighted_sd", type number}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

