table Feature_Profile
	lineageTag: 7e58bc45-7ee3-4c4a-a96c-52caef8793a2

	column cluster
		dataType: int64
		formatString: 0
		lineageTag: e3259586-6312-44f6-b59d-9d11429a73b5
		summarizeBy: sum
		sourceColumn: cluster

		annotation SummarizationSetBy = Automatic

	column feature
		dataType: string
		lineageTag: abff2c19-763a-47c2-8bff-3ac9ed4762ff
		summarizeBy: none
		sourceColumn: feature

		annotation SummarizationSetBy = Automatic

	column medoid_region_id
		dataType: string
		lineageTag: 440e4ae1-7d02-431f-98bc-a4c6236edcd6
		summarizeBy: none
		sourceColumn: medoid_region_id

		annotation SummarizationSetBy = Automatic

	column hard_cluster_size
		dataType: int64
		formatString: 0
		lineageTag: 14b9aaf1-f7f2-4179-89cd-51ede3f44472
		summarizeBy: sum
		sourceColumn: hard_cluster_size

		annotation SummarizationSetBy = Automatic

	column effective_fuzzy_size
		dataType: double
		lineageTag: e6bbda5c-338e-4bac-9aa2-00827b449f24
		summarizeBy: sum
		sourceColumn: effective_fuzzy_size

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weighted_mean_2015_2019
		dataType: double
		lineageTag: 97f68974-b178-41be-90db-c6411e105215
		summarizeBy: sum
		sourceColumn: weighted_mean_2015_2019

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weighted_median_2015_2019
		dataType: double
		lineageTag: 533b305f-d488-4c4b-aa7a-d3b59c1cf60a
		summarizeBy: sum
		sourceColumn: weighted_median_2015_2019

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weighted_q25_2015_2019
		dataType: double
		lineageTag: 912449ec-916c-48e5-a58d-4687589dbc56
		summarizeBy: sum
		sourceColumn: weighted_q25_2015_2019

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weighted_q75_2015_2019
		dataType: double
		lineageTag: e72f4de5-808f-4a54-a3cc-d33fb65b2294
		summarizeBy: sum
		sourceColumn: weighted_q75_2015_2019

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weighted_iqr_2015_2019
		dataType: double
		lineageTag: 09ac64e9-8732-4bee-a7d1-74343317b465
		summarizeBy: sum
		sourceColumn: weighted_iqr_2015_2019

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weighted_sd_2015_2019
		dataType: double
		lineageTag: 34f3a8fd-6d28-46a2-805a-847dbdc7c9e6
		summarizeBy: sum
		sourceColumn: weighted_sd_2015_2019

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pooled_region_mean_2015_2019
		dataType: double
		lineageTag: 4a2ae496-424a-4d25-9f93-fdd94eb205b9
		summarizeBy: sum
		sourceColumn: pooled_region_mean_2015_2019

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column difference_from_pooled_mean
		dataType: double
		lineageTag: d9228300-d67f-44e8-83cc-eef983a6bb23
		summarizeBy: sum
		sourceColumn: difference_from_pooled_mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column standardized_difference_from_pooled_mean
		dataType: double
		lineageTag: 43bbaf4a-b9c3-4d9f-9b64-2021b04bbcf7
		summarizeBy: sum
		sourceColumn: standardized_difference_from_pooled_mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column medoid_temporal_mean
		dataType: double
		lineageTag: 3a08e0f4-682a-42f3-8d98-fdbec93be223
		summarizeBy: sum
		sourceColumn: medoid_temporal_mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Feature_Profile = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents("C:\Users\vitor\Documents\Portfolio\Projects\P1\outputs\07.2_powerbi_model.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "Feature_Profile", Kind = "Sheet"]}[Data],
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(#"Navegação 1", [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"cluster", Int64.Type}, {"feature", type text}, {"medoid_region_id", type text}, {"hard_cluster_size", Int64.Type}, {"effective_fuzzy_size", type number}, {"weighted_mean_2015_2019", type number}, {"weighted_median_2015_2019", type number}, {"weighted_q25_2015_2019", type number}, {"weighted_q75_2015_2019", type number}, {"weighted_iqr_2015_2019", type number}, {"weighted_sd_2015_2019", type number}, {"pooled_region_mean_2015_2019", type number}, {"difference_from_pooled_mean", type number}, {"standardized_difference_from_pooled_mean", type number}, {"medoid_temporal_mean", type number}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

