table Global_Local_Country
	lineageTag: 0ed4c933-5188-4bf8-8aee-a2e836852424

	column code
		dataType: string
		lineageTag: 7137ec8f-91ae-4d8d-92e3-3cb27f255978
		summarizeBy: none
		sourceColumn: code

		annotation SummarizationSetBy = Automatic

	column n_regions
		dataType: int64
		formatString: 0
		lineageTag: 08a7a0b0-a2bf-4fee-bcc7-679d972b0c05
		summarizeBy: sum
		sourceColumn: n_regions

		annotation SummarizationSetBy = Automatic

	column country_model_status
		dataType: string
		lineageTag: 90c34a2a-b0dc-4594-845c-a453ea2ba852
		summarizeBy: none
		sourceColumn: country_model_status

		annotation SummarizationSetBy = Automatic

	column country_selected_c
		dataType: int64
		formatString: 0
		lineageTag: a50b8d24-fe14-4f65-8a7f-7c6caf207f20
		summarizeBy: sum
		sourceColumn: country_selected_c

		annotation SummarizationSetBy = Automatic

	column global_c
		dataType: int64
		formatString: 0
		lineageTag: d68bee56-913f-4c1d-a25c-7d424a303f92
		summarizeBy: sum
		sourceColumn: global_c

		annotation SummarizationSetBy = Automatic

	column global_mean_max_membership
		dataType: double
		lineageTag: e3c52b62-9521-43e2-9a4d-992100a47a4c
		summarizeBy: sum
		sourceColumn: global_mean_max_membership

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column global_mean_membership_margin
		dataType: double
		lineageTag: a0f613d2-8e55-42d9-8204-20108fcc1ed4
		summarizeBy: sum
		sourceColumn: global_mean_membership_margin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column global_transition_regions
		dataType: int64
		formatString: 0
		lineageTag: 3088517a-d549-4298-8edd-9a2b4250fa5b
		summarizeBy: sum
		sourceColumn: global_transition_regions

		annotation SummarizationSetBy = Automatic

	column regions_with_local_partition
		dataType: int64
		formatString: 0
		lineageTag: 37097185-0477-42e0-b91d-3a8bd05b1caf
		summarizeBy: sum
		sourceColumn: regions_with_local_partition

		annotation SummarizationSetBy = Automatic

	column ari_global_vs_local
		dataType: double
		lineageTag: 18ec5d48-fed9-4dd4-b94e-92b3d1a4f5d8
		summarizeBy: sum
		sourceColumn: ari_global_vs_local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column local_mean_max_membership
		dataType: double
		lineageTag: ca048c09-ecbd-4f07-ad49-49ac3905427a
		summarizeBy: sum
		sourceColumn: local_mean_max_membership

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column local_mean_membership_margin
		dataType: double
		lineageTag: 7f4c9239-6b28-4806-ad48-300742160cb6
		summarizeBy: sum
		sourceColumn: local_mean_membership_margin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column local_transition_regions
		dataType: int64
		formatString: 0
		lineageTag: 4aeb7105-5d1e-4a9a-80ff-556ef63ca7a0
		summarizeBy: sum
		sourceColumn: local_transition_regions

		annotation SummarizationSetBy = Automatic

	partition Global_Local_Country = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents("C:\Users\vitor\Documents\Portfolio\Projects\P1\outputs\07.2_powerbi_model.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "Global_Local_Country", Kind = "Sheet"]}[Data],
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(#"Navegação 1", [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"code", type text}, {"n_regions", Int64.Type}, {"country_model_status", type text}, {"country_selected_c", Int64.Type}, {"global_c", Int64.Type}, {"global_mean_max_membership", type number}, {"global_mean_membership_margin", type number}, {"global_transition_regions", Int64.Type}, {"regions_with_local_partition", Int64.Type}, {"ari_global_vs_local", type number}, {"local_mean_max_membership", type number}, {"local_mean_membership_margin", type number}, {"local_transition_regions", Int64.Type}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

