table Indicator_Annual
	lineageTag: 74b05cb6-b0b7-4331-85e7-4a1a70043254

	column cluster
		dataType: int64
		formatString: 0
		lineageTag: 82a65573-7f4e-4aba-b876-99ac60a0e2fa
		summarizeBy: sum
		sourceColumn: cluster

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: 3ac4b281-7bed-4d1b-8b3a-d1d0628929d7
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column family
		dataType: string
		lineageTag: 268315f0-9350-4bcb-8d89-cf078cfff12e
		summarizeBy: none
		sourceColumn: family

		annotation SummarizationSetBy = Automatic

	column variable
		dataType: string
		lineageTag: c4c39a28-141b-401b-8d13-dc46a3e622c3
		summarizeBy: none
		sourceColumn: variable

		annotation SummarizationSetBy = Automatic

	column common_weight
		dataType: double
		lineageTag: c8de0157-39c3-413e-9642-a01c661c602f
		summarizeBy: sum
		sourceColumn: common_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column profile_mean
		dataType: double
		lineageTag: a4dbee95-b975-44b0-ad96-74724b3b3052
		summarizeBy: sum
		sourceColumn: profile_mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column profile_median
		dataType: double
		lineageTag: b1a7541b-6219-4417-b35e-8b0034c10195
		summarizeBy: sum
		sourceColumn: profile_median

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column profile_q25
		dataType: double
		lineageTag: 72344b04-af77-46a1-ba58-636e30bbdf55
		summarizeBy: sum
		sourceColumn: profile_q25

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column profile_q75
		dataType: double
		lineageTag: a47cd7aa-b07c-41d9-bceb-98694b864a45
		summarizeBy: sum
		sourceColumn: profile_q75

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column profile_sd
		dataType: double
		lineageTag: abbd6fd6-6c65-4044-b570-938dabe0dafe
		summarizeBy: sum
		sourceColumn: profile_sd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weighted_contribution_mean
		dataType: double
		lineageTag: e1c97269-9e05-4708-8b15-c9d886f91d2f
		summarizeBy: sum
		sourceColumn: weighted_contribution_mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column share_of_family_score_mean
		dataType: double
		lineageTag: 6b6a67e9-a042-42e1-8604-16660f220766
		summarizeBy: sum
		sourceColumn: share_of_family_score_mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column value_basis
		dataType: string
		lineageTag: 023238c7-e109-4a4e-b3b2-35a80ba28cf4
		summarizeBy: none
		sourceColumn: value_basis

		annotation SummarizationSetBy = Automatic

	column source_table
		dataType: string
		lineageTag: e4a042c1-cf43-48b8-b300-e71b920a803d
		summarizeBy: none
		sourceColumn: source_table

		annotation SummarizationSetBy = Automatic

	partition Indicator_Annual = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents("C:\Users\vitor\Documents\Portfolio\Projects\P1\outputs\07.2_powerbi_model.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "Indicator_Annual", Kind = "Sheet"]}[Data],
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(#"Navegação 1", [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"cluster", Int64.Type}, {"year", Int64.Type}, {"family", type text}, {"variable", type text}, {"common_weight", type number}, {"profile_mean", type number}, {"profile_median", type number}, {"profile_q25", type number}, {"profile_q75", type number}, {"profile_sd", type number}, {"weighted_contribution_mean", type number}, {"share_of_family_score_mean", type number}, {"value_basis", type text}, {"source_table", type text}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

