table Region_Year_Indicator
	lineageTag: 7c1463c4-b320-472a-9694-b8c7906b9b7f

	column region_id
		dataType: string
		lineageTag: f7ac7d21-c7a3-41c9-92c3-62be35cac45e
		summarizeBy: none
		sourceColumn: region_id

		annotation SummarizationSetBy = Automatic

	column code
		dataType: string
		lineageTag: 315304e7-d0f4-47d8-9abf-7a69d22a8b40
		summarizeBy: none
		sourceColumn: code

		annotation SummarizationSetBy = Automatic

	column geo_code
		dataType: string
		lineageTag: 14b6bade-ee0d-43e0-b8fb-c513c8df59f4
		summarizeBy: none
		sourceColumn: geo_code

		annotation SummarizationSetBy = Automatic

	column geo_name
		dataType: string
		lineageTag: b6a02c58-74a8-4a17-b88c-242b285f83ca
		summarizeBy: none
		sourceColumn: geo_name

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: d04679d9-849a-431a-8ad7-2107a54f5159
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column feature
		dataType: string
		lineageTag: 6f121a18-ef2b-4dc7-b07b-6c61a87d1dd8
		summarizeBy: none
		sourceColumn: feature

		annotation SummarizationSetBy = Automatic

	column family
		dataType: string
		lineageTag: eef984e9-9718-4926-b0ea-a5d4910bf48b
		summarizeBy: none
		sourceColumn: family

		annotation SummarizationSetBy = Automatic

	column variable
		dataType: string
		lineageTag: 1fb8612a-041a-4107-89c7-65df61b2569b
		summarizeBy: none
		sourceColumn: variable

		annotation SummarizationSetBy = Automatic

	column component_kind
		dataType: string
		lineageTag: 11c18508-f11f-4337-a800-6c7d69849e60
		summarizeBy: none
		sourceColumn: component_kind

		annotation SummarizationSetBy = Automatic

	column value_raw
		dataType: double
		lineageTag: 736306f9-5006-4498-91ea-df36ed8cba7f
		summarizeBy: sum
		sourceColumn: value_raw

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column value_normalized
		dataType: double
		lineageTag: fad854ef-ab70-492e-bc5b-45662df64d9e
		summarizeBy: sum
		sourceColumn: value_normalized

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column common_weight
		dataType: double
		lineageTag: 89cb6982-b52d-4e60-8415-c8796a923f33
		summarizeBy: sum
		sourceColumn: common_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weighted_contribution
		dataType: double
		lineageTag: 83832641-c546-4a4e-ac46-1fd7d57e20cb
		summarizeBy: sum
		sourceColumn: weighted_contribution

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column family_score
		dataType: double
		lineageTag: 1cb7822a-ef5c-4211-a948-b20fcd6c296e
		summarizeBy: sum
		sourceColumn: family_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column contribution_share_of_family_score
		dataType: double
		lineageTag: 20868496-6e77-45c8-b503-4e8f3e660445
		summarizeBy: sum
		sourceColumn: contribution_share_of_family_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Region_Year_Indicator = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents("C:\Users\vitor\Documents\Portfolio\Projects\P1\outputs\07.2_powerbi_model.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "Region_Year_Indicator", Kind = "Sheet"]}[Data],
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(#"Navegação 1", [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"region_id", type text}, {"code", type text}, {"geo_code", type text}, {"geo_name", type text}, {"year", Int64.Type}, {"feature", type text}, {"family", type text}, {"variable", type text}, {"component_kind", type text}, {"value_raw", type number}, {"value_normalized", type number}, {"common_weight", type number}, {"weighted_contribution", type number}, {"family_score", type number}, {"contribution_share_of_family_score", type number}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

