table Conv_Reg_Indicator
	lineageTag: cb99ddf8-c435-47ae-ba58-f50828752783

	column region_id
		dataType: string
		lineageTag: 13650043-3b6c-4eb9-aba6-7fa6befa0aa5
		summarizeBy: none
		sourceColumn: region_id

		annotation SummarizationSetBy = Automatic

	column flow
		dataType: string
		lineageTag: c770cd13-5353-4e93-a00a-572676a59a80
		summarizeBy: none
		sourceColumn: flow

		annotation SummarizationSetBy = Automatic

	column feature
		dataType: string
		lineageTag: bf9077a6-0f67-4238-acb4-3e29fe90c329
		summarizeBy: none
		sourceColumn: feature

		annotation SummarizationSetBy = Automatic

	column family
		dataType: string
		lineageTag: df03d91c-5471-40a9-85cf-797578ff40da
		summarizeBy: none
		sourceColumn: family

		annotation SummarizationSetBy = Automatic

	column variable
		dataType: string
		lineageTag: 90ebe139-fdd0-467d-8ed0-f8188c18e197
		summarizeBy: none
		sourceColumn: variable

		annotation SummarizationSetBy = Automatic

	column component_kind
		dataType: string
		lineageTag: 91d76df1-a1cc-40c5-800b-8f7af1c71c84
		summarizeBy: none
		sourceColumn: component_kind

		annotation SummarizationSetBy = Automatic

	column common_weight
		dataType: double
		lineageTag: aefb2ba6-38ee-47d1-adb2-9f25e679731a
		summarizeBy: sum
		sourceColumn: common_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 2015
		dataType: double
		lineageTag: ac0a818b-5ac7-452a-a501-859339c833b0
		summarizeBy: sum
		sourceColumn: 2015

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 2016
		dataType: double
		lineageTag: f3999baa-3566-4eee-b6f2-af1bf66507fd
		summarizeBy: sum
		sourceColumn: 2016

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 2017
		dataType: double
		lineageTag: ac2148a4-19c4-4567-aac5-104c979480b5
		summarizeBy: sum
		sourceColumn: 2017

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 2018
		dataType: double
		lineageTag: cb415f6a-d375-4097-a024-3ffe0dbf7c3f
		summarizeBy: sum
		sourceColumn: 2018

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 2019
		dataType: double
		lineageTag: 7ddf0a63-cab5-4df1-a65b-5e7c7b00551a
		summarizeBy: sum
		sourceColumn: 2019

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column convergence_contribution
		dataType: double
		lineageTag: d52d94bf-a1a3-4f49-b545-7adb9b4984a8
		summarizeBy: sum
		sourceColumn: convergence_contribution

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column convergence_index
		dataType: double
		lineageTag: 5bbec4cc-9360-4dbb-bb7a-ec99c314a16d
		summarizeBy: sum
		sourceColumn: convergence_index

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column converged_toward_destination
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: eb0af81d-7122-4b8e-a589-ec54142fccfe
		summarizeBy: none
		sourceColumn: converged_toward_destination

		annotation SummarizationSetBy = Automatic

	partition Conv_Reg_Indicator = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents("C:\Users\vitor\Documents\Portfolio\Projects\P1\outputs\07.2_powerbi_model.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "Conv_Reg_Indicator", Kind = "Sheet"]}[Data],
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Navegação 1", {{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column8", type number}, {"Column9", type number}, {"Column10", type number}, {"Column11", type number}, {"Column12", type number}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo de coluna alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"region_id", type text}, {"flow", type text}, {"feature", type text}, {"family", type text}, {"variable", type text}, {"component_kind", type text}, {"common_weight", type number}, {"2015", type number}, {"2016", type number}, {"2017", type number}, {"2018", type number}, {"2019", type number}, {"convergence_contribution", type number}, {"convergence_index", type number}, {"converged_toward_destination", type logical}})
				in
				  #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

