table Dim_Feature
	lineageTag: a23ace7c-d635-4aaa-8105-84dc56d000ce

	column feature
		dataType: string
		lineageTag: 32c2e684-d364-4091-aa88-669d3fcbc188
		summarizeBy: none
		sourceColumn: feature

		annotation SummarizationSetBy = Automatic

	column family
		dataType: string
		lineageTag: ede9170c-b5ae-41f0-83eb-0a271453df4f
		summarizeBy: none
		sourceColumn: family

		annotation SummarizationSetBy = Automatic

	column feature_label
		dataType: string
		lineageTag: e354d518-1fbe-46f2-8864-cac439af6760
		summarizeBy: none
		sourceColumn: feature_label

		annotation SummarizationSetBy = Automatic

	column feature_sort
		dataType: int64
		formatString: 0
		lineageTag: 37f7cd25-0cfc-4d2a-8121-fd156df3b403
		summarizeBy: sum
		sourceColumn: feature_sort

		annotation SummarizationSetBy = Automatic

	column is_bod_family_score
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8726910e-2d0e-448f-a722-47ea4abde9ad
		summarizeBy: none
		sourceColumn: is_bod_family_score

		annotation SummarizationSetBy = Automatic

	partition Dim_Feature = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents("C:\Users\vitor\Documents\Portfolio\Projects\P1\outputs\07.2_powerbi_model.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "Dim_Feature", Kind = "Sheet"]}[Data],
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(#"Navegação 1", [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"feature", type text}, {"family", type text}, {"feature_label", type text}, {"feature_sort", Int64.Type}, {"is_bod_family_score", type logical}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

