table Global_Local_Region
	lineageTag: b98d8b70-22a5-4459-a99a-3b181bbfc9cb

	column region_id
		dataType: string
		lineageTag: 53c8f9e4-5e52-4420-986b-63e89568cea0
		summarizeBy: none
		sourceColumn: region_id

		annotation SummarizationSetBy = Automatic

	column code
		dataType: string
		lineageTag: 501c5283-3838-44fb-b724-8bbdbabcc8f6
		summarizeBy: none
		sourceColumn: code

		annotation SummarizationSetBy = Automatic

	column geo_code
		dataType: string
		lineageTag: 9331e2f3-ca03-4a7a-9f7d-27f6d3d17f52
		summarizeBy: none
		sourceColumn: geo_code

		annotation SummarizationSetBy = Automatic

	column geo_name
		dataType: string
		lineageTag: 338604fb-1c3e-44f8-af53-e9c76421a56f
		summarizeBy: none
		sourceColumn: geo_name

		annotation SummarizationSetBy = Automatic

	column global_cluster
		dataType: int64
		formatString: 0
		lineageTag: df38c5d6-6caa-4e3a-b264-c343780a7b7e
		summarizeBy: sum
		sourceColumn: global_cluster

		annotation SummarizationSetBy = Automatic

	column global_max_membership
		dataType: double
		lineageTag: 001cde8a-8168-496d-b81b-84c0a6e235be
		summarizeBy: sum
		sourceColumn: global_max_membership

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column global_membership_margin
		dataType: double
		lineageTag: 2b099385-0294-4245-8685-e2a72378c7e4
		summarizeBy: sum
		sourceColumn: global_membership_margin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column global_membership_entropy
		dataType: double
		lineageTag: 16a9f50e-21a4-4d7f-a7e3-b1216b169b1e
		summarizeBy: sum
		sourceColumn: global_membership_entropy

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_cluster_1
		dataType: double
		lineageTag: 9bf98de3-9bfe-41cc-95c1-0a34b4785efa
		summarizeBy: sum
		sourceColumn: u_cluster_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_cluster_2
		dataType: double
		lineageTag: 919f26c2-9de3-452e-92f5-2b8e7a93a877
		summarizeBy: sum
		sourceColumn: u_cluster_2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column local_status
		dataType: string
		lineageTag: 87c61735-d4b3-472a-bf22-73e1f1f2edda
		summarizeBy: none
		sourceColumn: local_status

		annotation SummarizationSetBy = Automatic

	column local_c
		dataType: int64
		formatString: 0
		lineageTag: fc6da17d-f938-403a-9c09-e7ace31fc529
		summarizeBy: sum
		sourceColumn: local_c

		annotation SummarizationSetBy = Automatic

	column local_hard_cluster
		dataType: int64
		formatString: 0
		lineageTag: 153f6d76-36c6-4b4f-bcec-23f261063484
		summarizeBy: sum
		sourceColumn: local_hard_cluster

		annotation SummarizationSetBy = Automatic

	column local_max_membership
		dataType: double
		lineageTag: 20494f38-0c82-4a72-b69e-29a1fba9bf7b
		summarizeBy: sum
		sourceColumn: local_max_membership

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column local_membership_margin
		dataType: double
		lineageTag: 79126d20-c8fe-493b-bc58-bbdceac9ad4c
		summarizeBy: sum
		sourceColumn: local_membership_margin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column local_membership_entropy
		dataType: double
		lineageTag: 58628933-477c-4f8f-871e-a51e1c4c5c10
		summarizeBy: sum
		sourceColumn: local_membership_entropy

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column country_model_status
		dataType: string
		lineageTag: 3e66d147-ae14-45c9-b532-0c87347712e2
		summarizeBy: none
		sourceColumn: country_model_status

		annotation SummarizationSetBy = Automatic

	column country_selected_c
		dataType: int64
		formatString: 0
		lineageTag: 8080700a-1db2-488d-95a5-1e392aa857c4
		summarizeBy: sum
		sourceColumn: country_selected_c

		annotation SummarizationSetBy = Automatic

	column global_transition_zone
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7313c031-50d3-4369-8000-6d7705a33490
		summarizeBy: none
		sourceColumn: global_transition_zone

		annotation SummarizationSetBy = Automatic

	column local_transition_zone
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0ba564d6-4cc1-4075-9c79-7cf7565e5e52
		summarizeBy: none
		sourceColumn: local_transition_zone

		annotation SummarizationSetBy = Automatic

	partition Global_Local_Region = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents("C:\Users\vitor\Documents\Portfolio\Projects\P1\outputs\07.2_powerbi_model.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "Global_Local_Region", Kind = "Sheet"]}[Data],
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(#"Navegação 1", [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"region_id", type text}, {"code", type text}, {"geo_code", type text}, {"geo_name", type text}, {"global_cluster", Int64.Type}, {"global_max_membership", type number}, {"global_membership_margin", type number}, {"global_membership_entropy", type number}, {"u_cluster_1", type number}, {"u_cluster_2", type number}, {"local_status", type text}, {"local_c", Int64.Type}, {"local_hard_cluster", Int64.Type}, {"local_max_membership", type number}, {"local_membership_margin", type number}, {"local_membership_entropy", type number}, {"country_model_status", type text}, {"country_selected_c", Int64.Type}, {"global_transition_zone", type logical}, {"local_transition_zone", type logical}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

