table RVC_Region
	lineageTag: 7375b8ed-a36b-4903-9ce2-d1a83e016bfd

	column region_id
		dataType: string
		lineageTag: b291f984-b8a1-49f9-a8c6-3842df6ef6c8
		summarizeBy: none
		sourceColumn: region_id

		annotation SummarizationSetBy = Automatic

	column code
		dataType: string
		lineageTag: 5923cfdd-5956-4a34-877a-f86ceb2fd66c
		summarizeBy: none
		sourceColumn: code

		annotation SummarizationSetBy = Automatic

	column nn1_region_id
		dataType: string
		lineageTag: 15fa50c6-4c05-4e7c-af3d-dace8f7e8d76
		summarizeBy: none
		sourceColumn: nn1_region_id

		annotation SummarizationSetBy = Automatic

	column nn1_country_code
		dataType: string
		lineageTag: 4c5b0a76-776f-4a25-ab5d-74056d1902f0
		summarizeBy: none
		sourceColumn: nn1_country_code

		annotation SummarizationSetBy = Automatic

	column nn1_distance
		dataType: double
		lineageTag: 08cee4b4-bce1-4c11-a556-15babc8b4587
		summarizeBy: sum
		sourceColumn: nn1_distance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nn1_is_foreign
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e963642f-c0e8-4912-8b14-dd355d6c4d5d
		summarizeBy: none
		sourceColumn: nn1_is_foreign

		annotation SummarizationSetBy = Automatic

	column foreign_share_k1
		dataType: double
		lineageTag: e4bfdad6-f9f4-4d08-8bfb-83a04670f604
		summarizeBy: sum
		sourceColumn: foreign_share_k1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column foreign_share_k5
		dataType: double
		lineageTag: c507a18e-7c42-4dd2-a0ef-ce2588ec7b4b
		summarizeBy: sum
		sourceColumn: foreign_share_k5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column foreign_share_k10
		dataType: double
		lineageTag: 65a4fddf-1e44-484e-bd5c-11d0a95c4cc6
		summarizeBy: sum
		sourceColumn: foreign_share_k10

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column baseline_foreign_share
		dataType: double
		lineageTag: 61753e17-8ce3-4461-9ec1-625ef7eb34a6
		summarizeBy: sum
		sourceColumn: baseline_foreign_share

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column k5_exceeds_same_country_pool
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4984f5f4-8765-4246-a984-5d3026fce943
		summarizeBy: none
		sourceColumn: k5_exceeds_same_country_pool

		annotation SummarizationSetBy = Automatic

	column k10_exceeds_same_country_pool
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4c57f5e0-897f-4473-b1a4-6511cfdd4b83
		summarizeBy: none
		sourceColumn: k10_exceeds_same_country_pool

		annotation SummarizationSetBy = Automatic

	column nearest_same_country_region_id
		dataType: string
		lineageTag: e15d6d72-4e2d-401b-8f2c-57be6d016593
		summarizeBy: none
		sourceColumn: nearest_same_country_region_id

		annotation SummarizationSetBy = Automatic

	column nearest_same_country_distance
		dataType: double
		lineageTag: 2bb69647-fade-4f48-bbf5-4788d1e735c3
		summarizeBy: sum
		sourceColumn: nearest_same_country_distance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nearest_foreign_region_id
		dataType: string
		lineageTag: fc9659e8-8ef2-4bdf-9c89-8243a20fc191
		summarizeBy: none
		sourceColumn: nearest_foreign_region_id

		annotation SummarizationSetBy = Automatic

	column nearest_foreign_country_code
		dataType: string
		lineageTag: c3ecac9b-866b-44a8-a085-bfc777ba88fc
		summarizeBy: none
		sourceColumn: nearest_foreign_country_code

		annotation SummarizationSetBy = Automatic

	column nearest_foreign_distance
		dataType: double
		lineageTag: f23927c3-fdc6-45e0-b20d-7624f74de67c
		summarizeBy: sum
		sourceColumn: nearest_foreign_distance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column foreign_closer_than_same_country
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 42c7f2dc-2c27-474a-9076-1e8bbdcf6a15
		summarizeBy: none
		sourceColumn: foreign_closer_than_same_country

		annotation SummarizationSetBy = Automatic

	column country_majority_profile
		dataType: int64
		formatString: 0
		lineageTag: dd313160-ef7e-4d82-b4d0-24b4bdbf816a
		summarizeBy: sum
		sourceColumn: country_majority_profile

		annotation SummarizationSetBy = Automatic

	column differs_from_country_majority
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 33623cae-f0bc-4966-aa1c-681159fd96e4
		summarizeBy: none
		sourceColumn: differs_from_country_majority

		annotation SummarizationSetBy = Automatic

	partition RVC_Region = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents("C:\Users\vitor\Documents\Portfolio\Projects\P1\outputs\07.3_region_vs_country.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "RVC_Region", Kind = "Sheet"]}[Data],
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(#"Navegação 1", [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"region_id", type text}, {"code", type text}, {"nn1_region_id", type text}, {"nn1_country_code", type text}, {"nn1_distance", type number}, {"nn1_is_foreign", type logical}, {"foreign_share_k1", type number}, {"foreign_share_k5", type number}, {"foreign_share_k10", type number}, {"baseline_foreign_share", type number}, {"k5_exceeds_same_country_pool", type logical}, {"k10_exceeds_same_country_pool", type logical}, {"nearest_same_country_region_id", type text}, {"nearest_same_country_distance", type number}, {"nearest_foreign_region_id", type text}, {"nearest_foreign_country_code", type text}, {"nearest_foreign_distance", type number}, {"foreign_closer_than_same_country", type logical}, {"country_majority_profile", Int64.Type}, {"differs_from_country_majority", type logical}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

