table RVC_Variance
	lineageTag: c1f40ce6-17d0-470f-b13a-12b29551df19

	column variable
		dataType: string
		lineageTag: 6100bdad-2401-497d-9551-cbe71cfdb741
		summarizeBy: none
		sourceColumn: variable

		annotation SummarizationSetBy = Automatic

	column variable_label
		dataType: string
		lineageTag: aef78a80-d793-48e9-a59d-e2bf99e08e9d
		summarizeBy: none
		sourceColumn: variable_label

		annotation SummarizationSetBy = Automatic

	column variable_group
		dataType: string
		lineageTag: 300d97cc-694d-4bac-b485-41d13eb6a963
		summarizeBy: none
		sourceColumn: variable_group

		annotation SummarizationSetBy = Automatic

	column n_regions
		dataType: int64
		formatString: 0
		lineageTag: ffaeb70c-58f2-49b9-bb4b-bb8272bbce54
		summarizeBy: sum
		sourceColumn: n_regions

		annotation SummarizationSetBy = Automatic

	column n_countries
		dataType: int64
		formatString: 0
		lineageTag: f1acdf47-e00a-4bcf-a29d-8bc30b06a3c5
		summarizeBy: sum
		sourceColumn: n_countries

		annotation SummarizationSetBy = Automatic

	column eta2
		dataType: double
		lineageTag: 6b13c06f-4dff-4eda-b270-87c15f97c2e4
		summarizeBy: sum
		sourceColumn: eta2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column epsilon2
		dataType: double
		lineageTag: d7fa59fc-a253-4425-8f49-a8eb6da2a0b7
		summarizeBy: sum
		sourceColumn: epsilon2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column within_share
		dataType: double
		lineageTag: 9a2e6d24-d8b1-4345-90fb-d1b3cc33a602
		summarizeBy: sum
		sourceColumn: within_share

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column perm_p
		dataType: double
		lineageTag: 6accfbf6-957d-433c-87cb-aac4af15e910
		summarizeBy: sum
		sourceColumn: perm_p

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column perm_B
		dataType: int64
		formatString: 0
		lineageTag: 8955f5dc-100e-493d-95ef-a40e9f9d0c2b
		summarizeBy: sum
		sourceColumn: perm_B

		annotation SummarizationSetBy = Automatic

	column null_expected_eta2
		dataType: double
		lineageTag: 7fcdc4ab-52f2-4e72-9864-6afe3c7d7688
		summarizeBy: sum
		sourceColumn: null_expected_eta2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition RVC_Variance = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents("C:\Users\vitor\Documents\Portfolio\Projects\P1\outputs\07.3_region_vs_country.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "RVC_Variance", Kind = "Sheet"]}[Data],
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(#"Navegação 1", [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"variable", type text}, {"variable_label", type text}, {"variable_group", type text}, {"n_regions", Int64.Type}, {"n_countries", Int64.Type}, {"eta2", type number}, {"epsilon2", type number}, {"within_share", type number}, {"perm_p", type number}, {"perm_B", Int64.Type}, {"null_expected_eta2", type number}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

