table RVC_Country
	lineageTag: 2de9f21c-dfca-45f2-bc10-49e027ea05e9

	column code
		dataType: string
		lineageTag: f52b55a2-8a8c-4955-8d43-48bed0963064
		summarizeBy: none
		sourceColumn: code

		annotation SummarizationSetBy = Automatic

	column n_regions
		dataType: int64
		formatString: 0
		lineageTag: 59236473-0b14-4312-9186-a1c65519b394
		summarizeBy: sum
		sourceColumn: n_regions

		annotation SummarizationSetBy = Automatic

	column profiles_present
		dataType: int64
		formatString: 0
		lineageTag: 0b3e20c2-5afb-44fb-887d-ee07f9e19cf9
		summarizeBy: sum
		sourceColumn: profiles_present

		annotation SummarizationSetBy = Automatic

	column majority_profile
		dataType: int64
		formatString: 0
		lineageTag: 7439ebf9-3484-4213-85e8-61a2c24520e1
		summarizeBy: sum
		sourceColumn: majority_profile

		annotation SummarizationSetBy = Automatic

	column minority_regions
		dataType: int64
		formatString: 0
		lineageTag: a1b0585d-1f5c-4eab-a453-8098c9e8cd4e
		summarizeBy: sum
		sourceColumn: minority_regions

		annotation SummarizationSetBy = Automatic

	column regions_toward
		dataType: int64
		formatString: 0
		lineageTag: 4d09da68-5b05-44fd-8168-5d2c28b5f241
		summarizeBy: sum
		sourceColumn: regions_toward

		annotation SummarizationSetBy = Automatic

	column regions_away
		dataType: int64
		formatString: 0
		lineageTag: c6363333-8aec-425a-acee-0c577b2972d8
		summarizeBy: sum
		sourceColumn: regions_away

		annotation SummarizationSetBy = Automatic

	column has_both_directions
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7cb5edff-b58a-47e4-a7db-e0236b2a8bf9
		summarizeBy: none
		sourceColumn: has_both_directions

		annotation SummarizationSetBy = Automatic

	column mean_foreign_share_k1
		dataType: double
		lineageTag: b0d672f0-dfb9-4309-8859-3ac1287eb7ef
		summarizeBy: sum
		sourceColumn: mean_foreign_share_k1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mean_foreign_share_k5
		dataType: double
		lineageTag: b1ec5b9a-183d-423d-8ce0-93fafde85968
		summarizeBy: sum
		sourceColumn: mean_foreign_share_k5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mean_baseline_foreign_share
		dataType: double
		lineageTag: 3059dec6-5b75-4ebb-a322-ee4608ddac01
		summarizeBy: sum
		sourceColumn: mean_baseline_foreign_share

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column own_country_nearest_share
		dataType: double
		lineageTag: b34a2637-8587-4cda-8059-b8f97dd792de
		summarizeBy: sum
		sourceColumn: own_country_nearest_share

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column country_name = LOOKUPVALUE ( Dim_Country[country_name], Dim_Country[code], RVC_Country[code] )
		displayFolder: Dashboard
		lineageTag: 6a1c2f0e-9b8d-4a4e-8f2b-0d3c7a5e9f11
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition RVC_Country = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents("C:\Users\vitor\Documents\Portfolio\Projects\P1\outputs\07.3_region_vs_country.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "RVC_Country", Kind = "Sheet"]}[Data],
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(#"Navegação 1", [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"code", type text}, {"n_regions", Int64.Type}, {"profiles_present", Int64.Type}, {"majority_profile", Int64.Type}, {"minority_regions", Int64.Type}, {"regions_toward", Int64.Type}, {"regions_away", Int64.Type}, {"has_both_directions", type logical}, {"mean_foreign_share_k1", type number}, {"mean_foreign_share_k5", type number}, {"mean_baseline_foreign_share", type number}, {"own_country_nearest_share", type number}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

